#!/bin/bash

# function for checking directory on equal in current directory 
function check {
for dir in $(ls)
do
if [ dir == $1 ]
then
echo -1
fi
done
echo 1
}

file_array=$(ls)
me=$(basename $0)
# cycle to delete directories and files
for name in ${file_array[@]}
do
if [ $name != $me ]
then
rm -r $name
fi 
done

# cycle to create new directories and write to info.txt and infoall.txt information about users and recursive tree of catalogs
who_array=$(who | cut -d' ' -f1)
info="info.txt"
infoall="infoall.txt"
touch $infoall
for name_user in ${who_array[@]}
do
result=$(check $name_user)
if [ $result -eq 1 ]
then
mkdir $name_user
user=$(who | grep $name_user)
cd $name_user
touch $info
echo $user > $info
cd ..
cur=$(pwd)
files=$(find)
cd $name_user
for file in $files
do
if [ ${file:-1} != '~' ]
then 
echo $file
echo -e "$cur/$file" >> $info
fi
done
str=$(cat $info)
cd ..
echo $str >> $infoall
fi
done
